version: '2'
services:
    technew-app:
        image: technew
            - technew-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/technew
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    technew-mariadb:
        extends:
            file: mariadb.yml
            service: technew-mariadb
